FROM python:3.7

RUN pip3 install --upgrade cartography python-dateutil==2.8.0

USER nobody
ENTRYPOINT ["cartography"]
